version: '3.1'

services:
  web:
    build:
      dockerfile: NotesFlask/Dockerfile
    command: gunicorn --bind 0.0.0.0:5001 wsgi:app
    ports:
      - '8085:5001'
    networks:
      - default

  notes-mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    expose:
      - 27018
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: notesmongo
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - default

networks:
  default:
    external:
      name: notes_network